# Generated by Django 3.2.12 on 2023-07-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_prise_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
